### ISSUE TITLE
Is there any situation in which the broadcastRefreshLV is necessary for MMS messages?

### ISSUE THREAD

**Issue by samarthd** [samarthd/FutureMessengerApp#51]
The whole point of the broadcastRefreshLV is to ensure that if a message gets sent and deleted while the user has the app open, the main messages list gets updated to prevent the user from attempting to interact with a non-existent message. However, if the MMS intent is fired, then the main messages list won't be open at the time of "sending."

Unless of course we somehow start the MMS activity for a result and then delete once the MMS activity returns. It seems more likely that we'd put all the data in an intent, delete the message from the database, then fire the intent. In which case the listview wouldn't have to be refreshed.

**Comment by xtkbilly** [comment]
Not 100% sure, but I'm fairly certain we won't, since if an app is opened once the intent is fired off, our app should call onStop() or onPause(), since our app should no longer be visible. But testing should definitely be done, to see how the notifications/intents work while the device is open and running.
